import { useEffect, useState } from "react";
import { FaStar } from "react-icons/fa";
import { toast } from "react-toastify";
import Button from "../../components/common/Button";
import Card from "../../components/common/Card";
import Input from "../../components/common/Input";
import { getMyFeedback, submitFeedback } from "../../services/feedbackService";
import { createProfile, getProfile, updateProfile } from "../../services/profileService";
import "./Settings.css";

const emptyPreferences = { preferredRole: "", careerGoal: "", location: "", experience: "" };
function Settings() {
  const [preferences, setPreferences] = useState(emptyPreferences); const [profileExists, setProfileExists] = useState(false); const [saving, setSaving] = useState(false);
  const [feedback, setFeedback] = useState([]); const [feedbackForm, setFeedbackForm] = useState({ rating: 5, category: "General", comment: "" }); const [submitting, setSubmitting] = useState(false);
  const user = JSON.parse(localStorage.getItem("user") || "null");
  const load = async () => { try { const response = await getProfile(); setPreferences({ ...emptyPreferences, ...response.data }); setProfileExists(true); } catch (error) { if (error.response?.status !== 404) toast.error("Could not load preferences"); } try { const response = await getMyFeedback(); setFeedback(response.data); } catch { /* feedback is optional */ } };
  useEffect(() => { load(); }, []);
  const setPreference = (event) => setPreferences((current) => ({ ...current, [event.target.name]: event.target.value }));
  const savePreferences = async (event) => { event.preventDefault(); setSaving(true); try { if (profileExists) await updateProfile(preferences); else { await createProfile(preferences); setProfileExists(true); } toast.success("Career preferences saved"); } catch (error) { toast.error(error.response?.data?.message || "Could not save preferences"); } finally { setSaving(false); } };
  const sendFeedback = async (event) => { event.preventDefault(); if (!feedbackForm.comment.trim()) return toast.error("Please add a feedback message"); setSubmitting(true); try { const response = await submitFeedback(feedbackForm); setFeedback((current) => [response.data.feedback, ...current]); setFeedbackForm({ rating: 5, category: "General", comment: "" }); toast.success("Thank you for your feedback"); } catch (error) { toast.error(error.response?.data?.message || "Could not submit feedback"); } finally { setSubmitting(false); } };
  return <div className="settings-page"><h1>Settings</h1><p className="settings-intro">Manage the preferences used to personalise your career guidance.</p>
    <Card className="settings-feedback-card"><h2>Account</h2><div className="settings-account"><div><small>Name</small><strong>{user?.name || "Career Guidance user"}</strong></div><div><small>Email</small><strong>{user?.email || "Not available"}</strong></div></div><p className="settings-feedback-hint">Your sign-in details are protected. Contact support if you need help with account access.</p></Card>
    <Card className="settings-feedback-card"><h2>Career preferences</h2><p className="settings-feedback-hint">These details help AI Chat, career recommendations, and job suggestions stay relevant.</p><form className="settings-feedback-form" onSubmit={savePreferences}><div className="settings-feedback-row"><label>Preferred role<Input name="preferredRole" value={preferences.preferredRole} onChange={setPreference} placeholder="e.g. Frontend Developer" /></label><label>Experience level<Input as="select" name="experience" value={preferences.experience} onChange={setPreference}><option value="">Select experience</option><option>Student / Fresher</option><option>0–2 years</option><option>3–5 years</option><option>5+ years</option></Input></label></div><div className="settings-feedback-row"><label>Location<Input name="location" value={preferences.location} onChange={setPreference} placeholder="e.g. Hyderabad" /></label><label>Career goal<Input name="careerGoal" value={preferences.careerGoal} onChange={setPreference} placeholder="e.g. Become a full-stack developer" /></label></div><Button type="submit" loading={saving}>Save preferences</Button></form></Card>
    <Card className="settings-feedback-card"><h2>Send feedback</h2><p className="settings-feedback-hint">Tell us what is useful or what needs improvement.</p><form className="settings-feedback-form" onSubmit={sendFeedback}><div className="settings-feedback-row"><label>Category<Input as="select" value={feedbackForm.category} onChange={(event) => setFeedbackForm((current) => ({ ...current, category: event.target.value }))}><option>General</option><option>AI Analysis</option><option>Job Recommendations</option><option>Resume Tools</option><option>Bug Report</option></Input></label><label>Rating<div className="settings-star-row">{[1,2,3,4,5].map((value) => <button type="button" className={`settings-star ${value <= feedbackForm.rating ? "settings-star--filled" : ""}`} onClick={() => setFeedbackForm((current) => ({ ...current, rating: value }))} aria-label={`${value} stars`} key={value}><FaStar /></button>)}</div></label></div><label>Your feedback<Input as="textarea" value={feedbackForm.comment} onChange={(event) => setFeedbackForm((current) => ({ ...current, comment: event.target.value }))} placeholder="Share your experience…" maxLength={1000} /></label><Button type="submit" loading={submitting}>Submit feedback</Button></form></Card>
    {feedback.length > 0 && <Card className="settings-feedback-card"><h2>Your feedback</h2><ul className="settings-feedback-history">{feedback.map((item) => <li key={item._id}><div className="settings-feedback-history-top"><strong>{item.category} · {item.rating}/5</strong><span className={`settings-feedback-status settings-feedback-status--${item.status}`}>{item.status}</span></div><div>{item.comment}</div><div className="settings-feedback-date">{new Date(item.createdAt).toLocaleDateString()}</div></li>)}</ul></Card>}
  </div>;
}
export default Settings;
