import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import {
  listProfiles, listFeedback, updateFeedback, listCourses, createCourse, updateCourse, deleteCourse,
  listActivity, getSystemStatus, getNotifications, getReports, getJobRecommendationAnalytics,
} from "../../services/adminService";
import "./AdminManagementPage.css";

function Pager({ pagination, setPage }) {
  return <div className="am-pager"><button disabled={pagination.page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</button><span>Page {pagination.page} of {pagination.totalPages} · {pagination.total} records</span><button disabled={pagination.page >= pagination.totalPages} onClick={() => setPage((p) => p + 1)}>Next</button></div>;
}

function ProfilesPage() {
  const [data, setData] = useState({ profiles: [], pagination: { page: 1, totalPages: 1, total: 0 } });
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); listProfiles({ search: search || undefined, page, limit: 10 }).then(r => setData(r.data)).catch(e => toast.error(e.response?.data?.message || "Failed to load profiles")).finally(() => setLoading(false)); };
  useEffect(load, [page]);
  return <><h1 className="admin-page-title">Profile Management</h1><div className="admin-panel am-toolbar"><form onSubmit={e => { e.preventDefault(); setPage(1); load(); }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search profile fields..."/><button>Search</button></form></div><div className="admin-panel">{loading ? <p className="admin-empty-state">Loading profiles...</p> : data.profiles.length === 0 ? <p className="admin-empty-state">No profiles found.</p> : <div className="am-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Education</th><th>Skills</th><th>Career Goal</th><th>Completion</th><th>Last Activity</th></tr></thead><tbody>{data.profiles.map(p => <tr key={p._id}><td>{p.userId?.name}<br/><small>{p.userId?.email}</small></td><td>{p.degree || "—"}<br/><small>{p.branch || ""}{p.college ? ` · ${p.college}` : ""}</small></td><td>{(p.skills || []).slice(0, 5).join(", ") || "—"}</td><td>{p.careerGoal || p.preferredRole || "—"}</td><td><strong>{p.completion}%</strong></td><td>{p.updatedAt ? new Date(p.updatedAt).toLocaleString() : "—"}</td></tr>)}</tbody></table></div>}<Pager pagination={data.pagination} setPage={setPage}/></div></>;
}

function FeedbackPage() {
  const [data, setData] = useState({ feedback: [], summary: { averageRating: 0, total: 0 }, pagination: { page: 1, totalPages: 1, total: 0 } });
  const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); listFeedback({ status: status || undefined, search: search || undefined, page, limit: 10 }).then(r => setData(r.data)).catch(e => toast.error(e.response?.data?.message || "Failed to load feedback")).finally(() => setLoading(false)); };
  useEffect(load, [page, status]);
  const changeStatus = async (id, next) => { try { await updateFeedback(id, { status: next }); toast.success("Feedback updated"); load(); } catch (e) { toast.error(e.response?.data?.message || "Update failed"); } };
  return <><h1 className="admin-page-title">User Feedback Management</h1><div className="admin-stats-grid"><div className="admin-stat-card"><p className="admin-stat-label">Total Feedback</p><h3 className="admin-stat-value">{data.summary.total}</h3></div><div className="admin-stat-card"><p className="admin-stat-label">Average Rating</p><h3 className="admin-stat-value">{data.summary.averageRating}/5</h3></div></div><div className="admin-panel am-toolbar"><form onSubmit={e => { e.preventDefault(); setPage(1); load(); }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search feedback..."/><button>Search</button></form><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option><option value="new">New</option><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option></select></div><div className="admin-panel">{loading ? <p className="admin-empty-state">Loading feedback...</p> : data.feedback.length === 0 ? <p className="admin-empty-state">No feedback found.</p> : <div className="am-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Rating</th><th>Category</th><th>Comment</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.feedback.map(f => <tr key={f._id}><td>{f.userId?.name || "Anonymous"}<br/><small>{f.userId?.email || ""}</small></td><td>{"★".repeat(f.rating)}{"☆".repeat(5 - f.rating)}</td><td>{f.category}</td><td className="am-comment">{f.comment}</td><td><span className={`am-status ${f.status}`}>{f.status}</span></td><td><select value={f.status} onChange={e => changeStatus(f._id, e.target.value)}><option value="new">New</option><option value="reviewed">Reviewed</option><option value="resolved">Resolved</option></select></td></tr>)}</tbody></table></div>}<Pager pagination={data.pagination} setPage={setPage}/></div></>;
}

const blankCourse = { resourceType: "course", title: "", provider: "", category: "General", skill: "", difficulty: "Beginner", duration: "", url: "", description: "", isActive: true };
function CoursesPage() {
  const [data, setData] = useState({ courses: [], pagination: { page: 1, totalPages: 1, total: 0 } }); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [form, setForm] = useState(blankCourse); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); listCourses({ search: search || undefined, page, limit: 10 }).then(r => setData(r.data)).catch(e => toast.error(e.response?.data?.message || "Failed to load courses")).finally(() => setLoading(false)); };
  useEffect(load, [page]);
  const submit = async e => { e.preventDefault(); try { if (editing) await updateCourse(editing, form); else await createCourse(form); toast.success(editing ? "Course updated" : "Course created"); setForm(blankCourse); setEditing(null); setShowForm(false); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not save course"); } };
  const edit = c => { setEditing(c._id); setForm({ ...c }); setShowForm(true); };
  const deactivate = async id => { if (!window.confirm("Deactivate this course?")) return; try { await deleteCourse(id); toast.success("Course deactivated"); load(); } catch (e) { toast.error(e.response?.data?.message || "Could not deactivate course"); } };
  const set = (key, value) => setForm(f => ({ ...f, [key]: value }));
  return <><div className="am-heading"><div><h1 className="admin-page-title">Courses & Certifications</h1><p>Manage the platform's curated learning catalog. Existing AI course recommendations remain untouched.</p></div><button className="am-primary" onClick={() => { setForm(blankCourse); setEditing(null); setShowForm(v => !v); }}>{showForm ? "Close" : "+ Add Course"}</button></div>{showForm && <div className="admin-panel am-form-panel"><form onSubmit={submit}><div className="am-form-grid"><label>Type<select value={form.resourceType} onChange={e => set("resourceType", e.target.value)}><option value="course">Course</option><option value="certification">Certification</option></select></label>{[["title","Title"],["provider","Provider"],["category","Category"],["skill","Skill"],["difficulty","Difficulty"],["duration","Duration"],["url","URL"]].map(([k,l]) => <label key={k}>{l}<input required={k === "title" || k === "provider"} value={form[k]} onChange={e => set(k,e.target.value)}/></label>)}<label className="am-full">Description<textarea value={form.description} onChange={e => set("description",e.target.value)}/></label></div><div className="am-form-actions"><button type="submit" className="am-primary">{editing ? "Update Course" : "Create Course"}</button><button type="button" onClick={() => setShowForm(false)}>Cancel</button></div></form></div>}<div className="admin-panel am-toolbar"><form onSubmit={e => { e.preventDefault(); setPage(1); load(); }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search courses, providers or skills..."/><button>Search</button></form></div><div className="admin-panel">{loading ? <p className="admin-empty-state">Loading courses...</p> : data.courses.length === 0 ? <p className="admin-empty-state">No catalog courses yet. Add one to begin.</p> : <div className="am-table-wrap"><table className="admin-table"><thead><tr><th>Type</th><th>Course / Certification</th><th>Provider</th><th>Category</th><th>Skill</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.courses.map(c => <tr key={c._id}><td>{c.resourceType}</td><td><strong>{c.title}</strong><br/><small>{c.duration || ""}</small></td><td>{c.provider}</td><td>{c.category}</td><td>{c.skill || "—"}</td><td><span className={`am-status ${c.isActive ? "resolved" : "new"}`}>{c.isActive ? "active" : "inactive"}</span></td><td><button className="am-link-btn" onClick={() => edit(c)}>Edit</button><button className="am-danger-link" onClick={() => deactivate(c._id)}>Deactivate</button></td></tr>)}</tbody></table></div>}<Pager pagination={data.pagination} setPage={setPage}/></div></>;
}

function ActivityPage() {
  const [data,setData]=useState({activity:[],pagination:{page:1,totalPages:1,total:0}}); const [page,setPage]=useState(1); const [type,setType]=useState(""); const [loading,setLoading]=useState(true);
  const load=()=>{setLoading(true);listActivity({page,limit:15,type:type||undefined}).then(r=>setData(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to load activity")).finally(()=>setLoading(false));}; useEffect(load,[page,type]);
  return <><h1 className="admin-page-title">Platform Usage & Activity</h1><div className="admin-panel am-toolbar"><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="">All events</option><option value="login">Logins</option><option value="resume_upload">Resume uploads</option><option value="resume_analysis">Resume analyses</option><option value="job_search">Job searches</option><option value="career_recommendation">Career recommendations</option><option value="course_recommendation">Course recommendations</option><option value="profile_update">Profile updates</option></select></div><div className="admin-panel">{loading?<p className="admin-empty-state">Loading activity...</p>:data.activity.length===0?<p className="admin-empty-state">No activity recorded yet.</p>:<div className="am-timeline">{data.activity.map(a=><div className="am-timeline-row" key={a._id}><div className="am-dot"/><div><strong>{a.message}</strong><p>{a.userId?.name || "System"}{a.userId?.email ? ` · ${a.userId.email}` : ""}</p></div><time>{new Date(a.createdAt).toLocaleString()}</time></div>)}</div>}<Pager pagination={data.pagination} setPage={setPage}/></div></>;
}

function SystemPage() { const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const load=()=>{setLoading(true);getSystemStatus().then(r=>setData(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to load system status")).finally(()=>setLoading(false));}; useEffect(load,[]); return <><div className="am-heading"><div><h1 className="admin-page-title">System / API Monitoring</h1><p>Live operational checks. Secrets and credential values are never returned.</p></div><button onClick={load}>Refresh</button></div>{loading?<div className="admin-panel">Checking services...</div>:<div className="am-service-grid">{data.services.map(s=><div className="admin-panel am-service" key={s.name}><div><h3>{s.name}</h3><p>{s.detail}</p></div><span className={`am-status ${s.status}`}>{s.status}</span></div>)}<div className="admin-panel am-service-note"><strong>Historical API error metrics:</strong> not tracked by the existing architecture. This page intentionally does not fabricate counts.</div></div>}</> }

function ReportsPage() { const [data,setData]=useState(null); const [loading,setLoading]=useState(false); const [from,setFrom]=useState(""); const [to,setTo]=useState(""); const run=()=>{setLoading(true);getReports({from:from||undefined,to:to||undefined}).then(r=>setData(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to generate report")).finally(()=>setLoading(false));}; return <><h1 className="admin-page-title">Search, Filter & Reports</h1><div className="admin-panel am-toolbar"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="am-primary" onClick={run}>{loading?"Generating...":"Generate Report"}</button></div>{data&&<div className="admin-stats-grid">{Object.entries(data.metrics).map(([k,v])=><div className="admin-stat-card" key={k}><p className="admin-stat-label">{k.replace(/([A-Z])/g," $1")}</p><h3 className="admin-stat-value">{v}</h3></div>)}</div>}<div className="admin-panel"><p className="am-muted">Reports use real stored records for the selected date range (default: last 30 days).</p></div></>}

function NotificationsPage() { const [data,setData]=useState(null); const load=()=>getNotifications().then(r=>setData(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to load alerts")); useEffect(load,[]); return <><h1 className="admin-page-title">Notifications & Alerts</h1><div className="admin-panel">{!data?<p className="admin-empty-state">Loading alerts...</p>:data.alerts.length===0?<p className="admin-empty-state">No important alerts right now.</p>:<div className="am-alerts">{data.alerts.map((a,i)=><div className={`am-alert ${a.severity}`} key={i}><div><strong>{a.message}</strong><small>{new Date(a.timestamp).toLocaleString()}</small></div><span>{a.type}</span></div>)}</div>}</div></>}

function SettingsPage(){const admin=JSON.parse(localStorage.getItem("adminUser")||"null");return <><h1 className="admin-page-title">Admin Settings</h1><div className="admin-panel"><h2 className="admin-panel-title">Current Admin Account</h2><div className="am-settings-grid"><div><span>Name</span><strong>{admin?.name||"Admin"}</strong></div><div><span>Email</span><strong>{admin?.email||"—"}</strong></div><div><span>Role</span><strong>{admin?.role||"admin"}</strong></div><div><span>Session</span><strong>12-hour admin token</strong></div></div><p className="am-muted">Admin credentials are provisioned server-side. Passwords, JWT secrets and API keys are never stored in the browser or exposed through this page.</p></div></>}

function JobRecAnalyticsPage(){const [data,setData]=useState(null);useEffect(()=>{getJobRecommendationAnalytics().then(r=>setData(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to load job recommendation analytics"))},[]);if(!data)return <div className="admin-panel">Loading job recommendation analytics...</div>;const max=Math.max(...data.topQueries.map(x=>x.count),1);return <><h1 className="admin-page-title">Job Recommendation Analytics</h1><div className="admin-stats-grid"><div className="admin-stat-card"><p className="admin-stat-label">Searches</p><h3 className="admin-stat-value">{data.summary.searches}</h3></div><div className="admin-stat-card"><p className="admin-stat-label">Jobs Returned</p><h3 className="admin-stat-value">{data.summary.jobsReturned}</h3></div><div className="admin-stat-card"><p className="admin-stat-label">Avg Results/Search</p><h3 className="admin-stat-value">{data.summary.averageResults}</h3></div></div><div className="am-two-col"><div className="admin-panel"><h2 className="admin-panel-title">Most Searched Roles</h2>{data.topQueries.length===0?<p className="admin-empty-state">No job searches recorded yet.</p>:data.topQueries.map(q=><div className="am-bar" key={q.query}><span>{q.query}</span><div><i style={{width:`${q.count/max*100}%`}}/></div><b>{q.count}</b></div>)}</div><div className="admin-panel"><h2 className="admin-panel-title">Most Frequently Returned Jobs</h2>{data.topJobs.length===0?<p className="admin-empty-state">No job result history yet.</p>:<div className="am-table-wrap"><table className="admin-table"><thead><tr><th>Job</th><th>Company</th><th>Appearances</th><th>Avg Match</th></tr></thead><tbody>{data.topJobs.map(j=><tr key={j.id}><td>{j.title}</td><td>{j.company}</td><td>{j.appearances}</td><td>{j.averageMatch}%</td></tr>)}</tbody></table></div>}</div></div></>}

export default function AdminManagementPage({ module }) { if(module === "profiles") return <ProfilesPage/>; if(module === "feedback") return <FeedbackPage/>; if(module === "courses") return <CoursesPage/>; if(module === "activity") return <ActivityPage/>; if(module === "system") return <SystemPage/>; if(module === "reports") return <ReportsPage/>; if(module === "notifications") return <NotificationsPage/>; if(module === "settings") return <SettingsPage/>; if(module === "job-rec-analytics") return <JobRecAnalyticsPage/>; return <div className="admin-panel">Unknown admin module.</div>; }
